title: JH.DEV ⌁ Home
url: "https://jhung-mililani.github.io"
baseurl: ""

## Specify the theme using any of the css files in css/techfolio-theme
techfolio-theme: default.css
## Specify the formatting for triple backquote code sections.
rouge-theme: github.css

markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
strict_front_matter: true
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
include:
  - .nojekyll
  - _data
plugins:
  - jekyll-gist
